name: Deploy Preview to GitHub Pages
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Docusaurus
        run: yarn build

      - name: Move build to PR-specific folder
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          mv build "preview-$PR_NUMBER"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: .
          destination_dir: preview-${{ github.event.pull_request.number }}
      - name: Comment PR with Preview Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "üöÄ –ü–æ–ø–µ—Ä–µ–¥–Ω—ñ–π –ø–µ—Ä–µ–≥–ª—è–¥ –¥–æ—Å—Ç—É–ø–Ω–∏–π –∑–∞ –ø–æ—Å–∏–ª–∞–Ω–Ω—è–º: [–í—ñ–¥–∫—Ä–∏—Ç–∏].(https://yourusername.github.io/yourrepo/preview-${{ github.event.pull_request.number }}/)"
